syntax = "proto3";

package patchbukkit.registry;

import "patchbukkit/common/types.proto";

option java_multiple_files = true;
option java_package = "patchbukkit.registry";

enum RegistryType {
  SOUND_EVENT = 0;
  ITEM = 1;
}

message GetRegistryDataRequest {
  RegistryType registry = 1;
}

message GetRegistryDataResponse {
  oneof registry {
    SoundEventRegistryData sound_event = 1;
    ItemRegistryData item = 2;
  }
}

message SoundEvent {
  uint32 id = 1;
  string name = 2;
}

message SoundEventRegistryData {
  repeated SoundEvent sound_events = 1;
}

message ItemDefinition {
  string name = 1;
  uint32 max_stack_size = 2;
  uint32 max_durability = 3;
  bool edible = 4;
  bool record = 5;
}

message ItemRegistryData {
  repeated ItemDefinition items = 1;
}
